---
language: node_js
node_js: [ iojs ]
cache:
  directories:
    - bower_components
    - node_modules
sudo: false

before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install

script: grunt

deploy:
  provider: releases
  api_key:
    secure: v5x0c00IMu0yKaap/GbN7nkBL8O+TH8XXDAIWtZ9SCnWL7KiN1Olqdrz4QfjuPNut8/S0EdyMfSgiOogDQYhYyrbolwGi5wOJKAMTKl8lYzhWfWtkbRt/WhjnBJ0e3vIOwZZ2+VIihAJTYctuZr/z+FtIJ89w/x33C5vAcB8dG8KtanYPr3rbu8ci5qlGYDw7/QFOdCGGCwpLBR0aWsnRRePoDv7UeMXo4DxQ9oJjRp0lDC28F+7G0kt/OARIFypG9GGOuhdFedoeKlj2fqMCPBoBgiAkfG1Tpjin8PfQST4vk2F5jDg6nMURWGRrvdrw/5FQ6CeqgKlg+SnVl2qFpenc52TgeNLcd7mz/WG7SNyhtolbrLkiID8lre4FGxlwGB8Kgk0d6GkdpXmA5N4jbB83KwI6RUSnhXtYa9AxbVmnhPPiN8dycgBJZZDMP5Lq3c/mUavYma64usof8tgtsDPHwFu15+rfJddIXPDwvbjs3O06s0NP49GcJeFMFhC9PmrCEDfPPwpvPl7r959WgcPyB6iHaGjJYVbGbfKt4d/IlVb9W40lw8mfBeX4Gzzy4I8ZZvNr8KlbVPL5eYLLsNoKs2FmNVtk6ZySnjMIEE48FwBGCMnFOhDoqUpUA0/D7fCce9AnX/PrJmqHxxOY+2x5gKywm5/tu+plu72634=
  file: hexchat-material-design-icons-v${TRAVIS_TAG}.zip
  skip_cleanup: true
  on:
    tags: true
